"""empty message

Revision ID: 503bcf611b7c
Revises: 9f1c59bfb0da
Create Date: 2019-07-05 14:17:38.106932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '503bcf611b7c'
down_revision = '9f1c59bfb0da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('publish_datetime', sa.DateTime(), nullable=True))
    op.add_column('post', sa.Column('update_datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'update_datetime')
    op.drop_column('post', 'publish_datetime')
    # ### end Alembic commands ###
